import Head from "next/head";
import { FiGithub, FiLinkedin, FiTwitter } from "react-icons/fi";
// import { AnimCursor } from "./Animatedcursor";
import dynamic from "next/dynamic";

const AnimatedCursor = dynamic(() => import("react-animated-cursor"), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>BeardKoda</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <AnimCursor /> */}
        <AnimatedCursor innerSize={10} outerSize={20} />
        <div className="navbar">
          <h1 className="logo">BeardKoda</h1>
          <div className="likend">
            <a className="navlink" href="/">
              {" "}
              Home{" "}
            </a>
            <a className="navlink" href="/Resume">
              {" "}
              Resume
            </a>
            <a className="navlink" href="/Work"> 
              {" "}
              Works
            </a>
            <a className="navlink" href="/Contact">
              {" "}
              Contact
            </a>
          </div>
        </div>

        <section className="home">
          <div className="textdiv">
            <div className="textcon">
              <div className="typingtext">Hey I'm BeardKoda</div>
            </div>

            <div className="about">
              <div className="static">I'm a</div>
              <ul className="dynamic">
                <li>
                  <span> Freelancer</span>
                </li>
                <li>
                  <span> Designer</span>
                </li>
                <li>
                  <span> Developer</span>
                </li>
                <li>
                  <span> Software-Engineer</span>
                </li>
              </ul>
            </div>
          </div>
        </section>

        <footer className="sfooter">
          <div className="socials">
            <p className="follow">Follow Me</p>
            <p className="icons">
              <FiLinkedin />
            </p>
            <p className="icons">
              <FiGithub />
            </p>
            <p className="icons">
              <FiTwitter />
            </p>
          </div>

          <div className="contacti">
            <p className="emailnum"> E: beardkoda@gmail.com</p>
            <p className="emailnum"> T: +(234)7049302671</p>
          </div>
        </footer>
      </main>
    </>
  );
}
